EXTRA_CFLAGS += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_LGE) += devices_lge.o

#devices
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-panel.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-input.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-misc.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-pm.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-mmc.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-snd.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-camera.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-bt.o

#ers
obj-$(CONFIG_LGE_SUPPORT_ERS) += lge_ers.o

#diag
#mtc
obj-$(CONFIG_LGE_DIAG_MTC) += lge_diag_mtc.o
#wmc
obj-$(CONFIG_LGE_DIAG_WMC) += lge_diag_wmc.o
#testmode
obj-$(CONFIG_LGE_DIAG_TESTMODE) += lge_diag_testmode.o
obj-$(CONFIG_LGE_DIAG_TESTMODE) += lge_diag_class.o
obj-$(CONFIG_LGE_DIAG_TESTMODE) += lge_diag_communication.o
obj-$(CONFIG_LGE_DIAG_TESTMODE) += lge_diag_event_log.o
#wifi
obj-$(CONFIG_LGE_DIAG_WIFI) += lge_diag_wifi.o
#key press
obj-$(CONFIG_LGE_DIAG_KEYPRESS) += lge_diag_keypress.o
#screen shot
obj-$(CONFIG_LGE_DIAG_SCREENSHOT) += lge_diag_screen_shot.o
#screen section shot
obj-$(CONFIG_LGE_DIAG_SCREENSHOT) += lge_diag_screen_section_shot.o
#UDM
obj-$(CONFIG_LGE_DIAG_UDM) += lge_diag_udm.o
#icd
obj-$(CONFIG_LGE_DIAG_ICD) += lge_diag_icd.o

#ats
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_cmd.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_eta.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_mmc.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_event_log.o
obj-$(CONFIG_LGE_ATS_UEVENT_DEVICE) += lge_ats_uevent.o
obj-$(CONFIG_LGE_ATS_INPUT_DEVICE) += lge_ats_input.o

#etc
obj-$(CONFIG_LGE_SWITCH_GPIO) += lge_gpio_switch.o
obj-$(CONFIG_LGE_HEADSET_2GPIO) += lge_gpio_h2w.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o

obj-$(CONFIG_LGE_SUPPORT_RAPI) += lge_rapi_client.o
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o
obj-$(CONFIG_LGE_PWRSINK) += lge_pwrsink.o
obj-$(CONFIG_LGE_MTD_DIRECT_ACCESS) += lge_mtd_direct_access.o
obj-$(CONFIG_LGE_PCB_VERSION) += lge_pcb_version.o

#srd
obj-$(CONFIG_LGE_DIAG_SRD) += lge_diag_srd.o
