#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_SENSOR_GP2AP)	+= gp2ap002.o
obj-$(CONFIG_SENSOR_APDS9190)	+= apds9190.o

obj-$(CONFIG_SENSOR_K3DH)	+= k3dh.o
obj-$(CONFIG_SENSOR_KR3DH)	+= kr3dh.o

obj-$(CONFIG_SENSOR_AMI306) += ami306.o
